// <auto-generated />
using System;
using AtlasCompanyTracker.Database.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AtlasCompanyTracker.Database.Migrations.Goal
{
    [DbContext(typeof(GoalContext))]
    partial class GoalContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AtlasCompanyTracker.Models.Models.GoalModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EndingQuantity");

                    b.Property<Guid>("GoalGuid");

                    b.Property<int?>("ResourceID");

                    b.Property<int>("StartingQuantity");

                    b.Property<int>("Timeframe");

                    b.HasKey("ID");

                    b.HasIndex("ResourceID");

                    b.ToTable("Goals");
                });

            modelBuilder.Entity("AtlasCompanyTracker.Models.Models.ResourceModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<Guid>("ResourceGuid");

                    b.Property<string>("Thumbnail");

                    b.HasKey("ID");

                    b.ToTable("ResourceModel");
                });

            modelBuilder.Entity("AtlasCompanyTracker.Models.Models.GoalModel", b =>
                {
                    b.HasOne("AtlasCompanyTracker.Models.Models.ResourceModel", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceID");
                });
#pragma warning restore 612, 618
        }
    }
}
